spring:
  security:
    oauth2:
      client:
        registration:
          google:

            scope:
              - profile
              - email
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"  # Đảm bảo URI này khớp với URI trong Google Developer Console
            authorization-grant-type: authorization_code
            client-name: Google
